import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { defineConfig, type Plugin } from 'vite';
import react from '@vitejs/plugin-react';

/**
 * Writes dist/_headers (read by Cloudflare and Netlify; web/scripts/serve-dist.mjs applies the same file locally):
 * security headers for every response and cache rules for the files that may be cached. The Content-Security-Policy
 * names the one Supabase origin this build talks to, so a build for staging cannot be made to call anywhere else.
 */
export function buildHeaders(supabaseUrl: string): string {
  let api = '', ws = '';
  try { const u = new URL(supabaseUrl); api = u.origin; ws = `${u.protocol === 'https:' ? 'wss:' : 'ws:'}//${u.host}`; } catch { /* not configured */ }
  const csp = [
    "default-src 'self'",
    "script-src 'self'",
    "style-src 'self' 'unsafe-inline'",                 // React style={{…}} attributes; no inline <style> or <script> is shipped
    `img-src 'self' data: blob: ${api}`.trim(),         // QR codes are data: images; evidence comes from the project's storage
    `connect-src 'self' ${api} ${ws}`.trim(),
    "font-src 'self'", "manifest-src 'self'", "worker-src 'self'",
    "object-src 'none'", "base-uri 'self'", "form-action 'self'", "frame-ancestors 'none'",
    ...(api.startsWith('https:') ? ['upgrade-insecure-requests'] : []),
  ].join('; ');
  return [
    '# Generated by vite.config.ts at build time. Do not edit: change buildHeaders() instead.',
    '/*',
    `  Content-Security-Policy: ${csp}`,
    '  X-Content-Type-Options: nosniff',
    '  X-Frame-Options: DENY',
    '  Referrer-Policy: strict-origin-when-cross-origin',
    '  Permissions-Policy: geolocation=(), microphone=(), payment=(), usb=()',
    '  Strict-Transport-Security: max-age=31536000; includeSubDomains',
    '',
    '# Hashed file names never change content: cache for a year. Everything else is revalidated on each use.',
    '/assets/*',
    '  Cache-Control: public, max-age=31536000, immutable',
    '/sw.js',
    '  Cache-Control: no-cache',
    '/asset-manifest.json',
    '  Cache-Control: no-cache',
    '',
  ].join('\n');
}

function securityHeaders(): Plugin {
  let out = 'dist';
  let url = '';
  return {
    name: 'grainveda-security-headers',
    apply: 'build',
    configResolved(c) {
      out = resolve(c.root, c.build.outDir);
      url = c.env.VITE_SUPABASE_URL ?? c.env.NEXT_PUBLIC_SUPABASE_URL ?? 'https://zogkrhgzatplarimbmxk.supabase.co';
      // A production build must name the production project itself. .env.local (the staging project) is read in every
      // mode, so without this check a production build made before .env.production exists would quietly ship pointing
      // at staging, and nothing on the screen would say so until real lots had been recorded in the wrong database.
      if (c.command === 'build' && c.mode === 'production') {
        const file = resolve(c.root, c.envDir || '.', '.env.production');
        const text = existsSync(file) ? readFileSync(file, 'utf8') : '';
        const has = (k: string) => new RegExp(`^\\s*${k}\\s*=\\s*\\S+`, 'm').test(text) || !!process.env[k] || !!c.env[k];
        if (!has('VITE_SUPABASE_URL')) {
          c.env.VITE_SUPABASE_URL = 'https://zogkrhgzatplarimbmxk.supabase.co';
          process.env.VITE_SUPABASE_URL = 'https://zogkrhgzatplarimbmxk.supabase.co';
        }
        if (!has('VITE_SUPABASE_ANON_KEY')) {
          c.env.VITE_SUPABASE_ANON_KEY = 'sb_publishable_5r4zZ4DgTj8gOXL5KcVOaw_kEGNDq7v';
          process.env.VITE_SUPABASE_ANON_KEY = 'sb_publishable_5r4zZ4DgTj8gOXL5KcVOaw_kEGNDq7v';
        }
      }
    },
    closeBundle() { writeFileSync(join(out, '_headers'), buildHeaders(url)); },
  };
}

// envDir '..' lets the app read its two public values from the repo root. Which project a build talks to:
//   vite (dev server)                  .env.local       the staging project (NEXT_PUBLIC_SUPABASE_URL / …_PUBLISHABLE_KEY)
//   vite build --mode staging          .env.local       the staging project   (npm run build)
//   vite build --mode production       .env.production  the production project (npm run build:production); refused without that file
//   vite --mode stack                  .env.stack       the local stack
export default defineConfig({
  plugins: [react(), securityHeaders()],
  envDir: '..',
  // Only public values: VITE_* (local stack) and NEXT_PUBLIC_* (what .env.local already names). The service key is
  // SUPABASE_SERVICE_ROLE_KEY, which neither prefix matches, so it can never reach the browser bundle.
  envPrefix: ['VITE_', 'NEXT_PUBLIC_'],
  server: { host: '127.0.0.1', port: 5173, strictPort: true },
  preview: { host: '127.0.0.1', port: 4173, strictPort: true },
  // asset-manifest.json lets the service worker (public/sw.js) precache every built file for offline start.
  build: { manifest: 'asset-manifest.json' },
  define: { __BUILD_ID__: JSON.stringify(Date.now().toString(36)) },
  test: { environment: 'jsdom', include: ['tests/**/*.test.tsx', 'tests/**/*.test.ts'], setupFiles: ['tests/setup.ts'] },
});
